// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<{[key: string]: string}>;

export function Quit():Promise<void>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;
