repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.3
  hooks:
  - id: gitleaks
- repo: https://github.com/golangci/golangci-lint
  rev: v1.52.2
  hooks:
  - id: golangci-lint
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.38.0
  hooks:
  - id: eslint
    args: ["--fix"]
    files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
    types: [file]
    additional_dependencies:
    - eslint@8.53.0
    - eslint-plugin-react@7.33.2
    - typescript@4.6.4
    - "@typescript-eslint/parser@6.10.0"
    - "@typescript-eslint/eslint-plugin@6.10.0"
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
