// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
	return window["go"]["main"]["App"]["GetConfig"]();
}

export function Quit() {
	return window["go"]["main"]["App"]["Quit"]();
}

export function WindowMaximise() {
	return window["go"]["main"]["App"]["WindowMaximise"]();
}

export function WindowMinimise() {
	return window["go"]["main"]["App"]["WindowMinimise"]();
}
